import Header from '@/components/common/Header'
import AuthProvider from '@/providers/next-auth'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'

const inter = Inter({ subsets: ['latin'] })

const pretendard = localFont({
  src: [
    {
      path: '../../public/fonts/woff2/Pretendard-Black.woff2',
      weight: '900',
    },
    {
      path: '../../public/fonts/woff2/Pretendard-ExtraBold.woff2',
      weight: '800',
    },
    {
      path: '../../public/fonts/woff2/Pretendard-Bold.woff2',
      weight: '700',
    },
    {
      path: '../../public/fonts/woff2/Pretendard-SemiBold.woff2',
      weight: '600',
    },
    {
      path: '../../public/fonts/woff2/Pretendard-Medium.woff2',
      weight: '500',
    },
    {
      path: '../../public/fonts/woff2/Pretendard-Regular.woff2',
      weight: '400',
    },
    {
      path: '../../public/fonts/woff2/Pretendard-Light.woff2',
      weight: '300',
    },
    {
      path: '../../public/fonts/woff2/Pretendard-ExtraLight.woff2',
      weight: '200',
    },
  ],
  display: 'swap',
  variable: '--font-pretendard',
})

export const metadata: Metadata = {
  title: '코멘팅',
  description: 'Generated by Cod2-Crafters',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${pretendard.variable}`}>
      <body>
        <Header />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
